/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BusinessDashboard: typeof import('@/components/dashboard/BusinessDashboard.vue')['default']
    BusinessPreview: typeof import('@/components/ViewComponents/business/BusinessPreview.vue')['default']
    Checkbox: typeof import('@/components/ui/Checkbox.vue')['default']
    Flip: typeof import('number-flip')['Flip']
    Footer: typeof import('@/components/header_footer/Footer.vue')['default']
    Header: typeof import('@/components/header_footer/Header.vue')['default']
    LucideIcon: typeof import('@/components/ui/LucideIcon.vue')['default']
    Review: typeof import('@/components/ui/Review.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchItem: typeof import('@/components/ui/SearchItem.vue')['default']
    Tooltip: typeof import('@/components/ui/Tooltip.vue')['default']
  }
}
