/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AsyncComponent: typeof import('./src/components/AsyncComponent.vue')['default']
    BusinessDashboard: typeof import('@/components/business/BusinessDashboard.vue')['default']
    BusinessPreview: typeof import('./src/components/ViewComponents/business/BusinessPreview.vue')['default']
    BusinessView: typeof import('@/components/business/BusinessView.vue')['default']
    Checkbox: typeof import('@/components/ui/Checkbox.vue')['default']
    DatePicker: typeof import('@/components/ui/MyDatePicker.vue')['default']
    Flip: typeof import('number-flip')['Flip']
    Footer: typeof import('@/components/header_footer/Footer.vue')['default']
    Header: typeof import('@/components/header_footer/Header.vue')['default']
    LucideIcon: typeof import('@/components/ui/LucideIcon.vue')['default']
    MyDatePicker: typeof import('@/components/ui/MyDatePicker.vue')['default']
    NotFound: typeof import('@/components/ui/NotFound.vue')['default']
    Review: typeof import('@/components/ui/Review.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchItem: typeof import('@/components/ui/SearchItem.vue')['default']
    Tooltip: typeof import('@/components/ui/Tooltip.vue')['default']
  }
}
