/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BusinessCreatePreview: typeof import('@/components/business/BusinessCreatePreview.vue')['default']
    Checkbox: typeof import('@/components/ui/Checkbox.vue')['default']
    Flip: typeof import('number-flip')['Flip']
    Footer: typeof import('@/components/header_footer/Footer.vue')['default']
    Header: typeof import('@/components/header_footer/Header.vue')['default']
    LucideIcon: typeof import('@/components/ui/LucideIcon.vue')['default']
    MyDialog: typeof import('@/components/ui/MyDialog.vue')['default']
    ProgressBar: typeof import('@/components/ui/ProgressBar.vue')['default']
    Review: typeof import('@/components/ui/Review.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tooltip: typeof import('@/components/ui/Tooltip.vue')['default']
  }
}
