/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'home': RouteRecordInfo<'home', '/', Record<never, never>, Record<never, never>>,
    'not-found': RouteRecordInfo<'not-found', '/:slug(.*)', Record<never, never>, Record<never, never>>,
    'about': RouteRecordInfo<'about', '/about', Record<never, never>, Record<never, never>>,
    '/auth/confirm-account/[token]': RouteRecordInfo<'/auth/confirm-account/[token]', '/auth/confirm-account/:token', { token: ParamValue<true> }, { token: ParamValue<false> }>,
    'login': RouteRecordInfo<'login', '/auth/login', Record<never, never>, Record<never, never>>,
    'signup': RouteRecordInfo<'signup', '/auth/register', Record<never, never>, Record<never, never>>,
    'business': RouteRecordInfo<'business', '/business/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'business-account-confirmation': RouteRecordInfo<'business-account-confirmation', '/business/confirmation/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'business-create': RouteRecordInfo<'business-create', '/business/create', Record<never, never>, Record<never, never>>,
    'business-dashboard': RouteRecordInfo<'business-dashboard', '/business/dashboard', Record<never, never>, Record<never, never>>,
    'business-settings': RouteRecordInfo<'business-settings', '/business/settings/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'bad-request': RouteRecordInfo<'bad-request', '/error/bad-request', Record<never, never>, Record<never, never>>,
    'search': RouteRecordInfo<'search', '/search', Record<never, never>, Record<never, never>>,
    'user-profile': RouteRecordInfo<'user-profile', '/user/:username', { username: ParamValue<true> }, { username: ParamValue<false> }>,
  }
}
