/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    'not-found': RouteRecordInfo<'not-found', '/:slug(.*)', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/auth/confirm-account/[token]': RouteRecordInfo<'/auth/confirm-account/[token]', '/auth/confirm-account/:token', { token: ParamValue<true> }, { token: ParamValue<false> }>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
    '/auth/register': RouteRecordInfo<'/auth/register', '/auth/register', Record<never, never>, Record<never, never>>,
    '/business/[id]': RouteRecordInfo<'/business/[id]', '/business/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/business/BusinessSettingsViewOLD': RouteRecordInfo<'/business/BusinessSettingsViewOLD', '/business/BusinessSettingsViewOLD', Record<never, never>, Record<never, never>>,
    '/business/confirmation/[id]': RouteRecordInfo<'/business/confirmation/[id]', '/business/confirmation/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/business/create': RouteRecordInfo<'/business/create', '/business/create', Record<never, never>, Record<never, never>>,
    '/business/dashboard/': RouteRecordInfo<'/business/dashboard/', '/business/dashboard', Record<never, never>, Record<never, never>>,
    '/business/settings/[id]': RouteRecordInfo<'/business/settings/[id]', '/business/settings/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/error/bad-request': RouteRecordInfo<'/error/bad-request', '/error/bad-request', Record<never, never>, Record<never, never>>,
    '/search': RouteRecordInfo<'/search', '/search', Record<never, never>, Record<never, never>>,
    'user-profile': RouteRecordInfo<'user-profile', '/user/:username', { username: ParamValue<true> }, { username: ParamValue<false> }>,
  }
}
